-- AlterEnum
ALTER TYPE "CommandType" ADD VALUE 'SYNC_USER_FULL';

-- AlterTable
ALTER TABLE "Partner" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isOwner" BOOLEAN NOT NULL DEFAULT false;
